project_id = "xngppwphedaexwkgfjdv"

[functions.process-sale]
verify_jwt = true

[functions.database-cleanup]
verify_jwt = false

[functions.delete-sale]
verify_jwt = true

[functions.validate-invitation]
verify_jwt = false
